typedef enum {
    ACTIVITY_BALANCE, ACTIVITY_BANKS, ACTIVITY_CARDS, ACTIVITY_FRIENDS, ACTIVITY_GROUPS,
    ACTIVITY_PERSONAL_TRANSACTIONS, ACTIVITY_INCOMING_TRANSACTIONS, ACTIVITY_OUTGOING_TRANSACTIONS,
    ACTIVITY_PUBLIC_TRANSACTIONS, ACTIVITY_FRIENDS_TRANSACTIONS,
    ACTIVITY_NOTIFICATIONS, ACTIVITY_USER_SETTINGS
} ReRenderableActivityType;
